// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoWebApp.Data;

namespace ToDoWebApp.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20200225044125_seededDB")]
    partial class seededDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoWebApp.Models.ToDoList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ToDoList");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Completed = false,
                            DueDate = "2/20/2020",
                            Priority = 1,
                            Task = "Do Homework"
                        },
                        new
                        {
                            ID = 2,
                            Completed = false,
                            DueDate = "2/26/2020",
                            Priority = 3,
                            Task = "Get an oil change"
                        },
                        new
                        {
                            ID = 3,
                            Completed = true,
                            DueDate = "2/24/2020",
                            Priority = 2,
                            Task = "Clean room"
                        },
                        new
                        {
                            ID = 4,
                            Completed = true,
                            DueDate = "2/23/2020",
                            Priority = 3,
                            Task = "Go to the gym"
                        },
                        new
                        {
                            ID = 5,
                            Completed = false,
                            DueDate = "2/22/2020",
                            Priority = 1,
                            Task = "Wash dishes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
